# Generated by Django 3.2.18 on 2023-04-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placevisits', '0003_alter_place_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['start_date', 'end_date']},
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
